echo "# THIS FILE WAS AUTOMATICALLY GENERATED BY configure.sh" > Makefile
echo "Detecting OS..."
if [[ "$OSTYPE" == "linux-gnu" || "$OSTYPE" == "freebsd"* ]]; then
        echo "CPP := g++" >> Makefile
        LIB=""
        INC=""
elif [[ "$OSTYPE" == "darwin"* ]]; then
        # Mac OSX
        echo "detecting Homebrew clang..."
        echo
        /usr/local/opt/llvm/bin/clang++ --version
        echo
        if [[ "$?" != 0 ]]; then
            echo "FAILED"
            echo "This code depends on an installation of clang++ from Homebrew\
             for openmp support"
            exit 1
        fi
        echo "CPP := /usr/local/opt/llvm/bin/clang++" >> Makefile
        LIB="-L/usr/local/opt/llvm/lib"
        INC="-I/usr/local/opt/llvm/include"
else
        echo Sorry, this environment is not supported.
fi
# elif [[ "$OSTYPE" == "cygwin" ]]; then
#         # POSIX compatibility layer and Linux environment emulation for Windows
#
# elif [[ "$OSTYPE" == "msys" ]]; then
#         # Lightweight shell and GNU utilities compiled for Windows (part of MinGW)
# else
#         # Unknown.
# fi

echo "This program depends on eigen 3 (http://eigen.tuxfamily.org)."
echo "Please enter the full path to the folder containing eigen3..."
read EIGENPATH
echo
find $EIGENPATH -name "eigen3"

if [[ "$?" != 0 ]]; then
    echo "ERROR: eigen3 folder not found at $EIGENPATH"
    exit 1
fi

INC="$INC -I$EIGENPATH"

echo "LIB := -fopenmp $LIB" >> Makefile
echo "INC := $INC" >> Makefile

cat .Makefile_template >> Makefile

make
